# Generated by Django 2.2.1 on 2019-05-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_languege', models.CharField(max_length=200)),
                ('query_text', models.TextField(blank=True)),
                ('created', models.DateField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
